FROM golang:1.24 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

ADD . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o /todo-server

FROM alpine:3.21

WORKDIR /

COPY --from=build-stage /todo-server /todo-server

EXPOSE 8000

CMD ["/todo-server"]